backend:
  name: git-gateway
  branch: cms-edits

publish_mode: editorial_workflow

media_folder: "_assets/img"
public_folder: ""

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm"}
      - {label: "Comments enabled", name: "comments", widget: "boolean"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Published", name: "published", widget: "boolean"}
      - {label: "Author is a Racker", name: "authorIsRacker", widget: "boolean"}
      - {label: "Categories", name: "categories", widget: "list"}
      - label: "Meta Title"
        name: "metaTitle"
        widget: "string"
        hint: "Usually the same as the Title"
      - label: "Meta Description"
        name: "metaDescription"
        widget: "text"
      - label: "Open Graph Title"
        name: "ogTitle"
        widget: "string"
        hint: "Usually the same as the Title"
      - label: "Open Graph Description"
        name: "ogDescription"
        widget: "text"
        hint: "Usually the same as the Meta Description"
      - {label: "Body", name: "body", widget: "markdown"}